
#--------------------------------------------
# On-board system clock
# set_property PACKAGE_PIN AR8         [ get_ports "SYS_CLK_clk_n" ]
# set_property IOSTANDARD  DIFF_SSTL12 [ get_ports "SYS_CLK_clk_n" ]
# set_property PACKAGE_PIN AP9         [ get_ports "SYS_CLK_clk_p" ]
# set_property IOSTANDARD  DIFF_SSTL12 [ get_ports "SYS_CLK_clk_p" ]
# create_clock -period 10.000 -name SYS_CLK [get_ports "SYS_CLK_clk_p"]
set_property PACKAGE_PIN AC6         [ get_ports "ETH_CLK_clk_n" ]
set_property PACKAGE_PIN AC7         [ get_ports "ETH_CLK_clk_p" ]
create_clock -period 6.400 -name ETH_CLK [get_ports "ETH_CLK_clk_p"]
set_property PACKAGE_PIN AD8         [ get_ports "GIG_CLK_clk_n" ]
set_property PACKAGE_PIN AD9         [ get_ports "GIG_CLK_clk_p" ]
create_clock -period 6.400 -name GIG_CLK [get_ports "GIG_CLK_clk_p"]

#--------------------------------------------
##  CPU_RESET_FPGA Connects to SW1 push button On the top edge of the PCB Assembly, also connects to Satellite Contoller
##                 Desinged to be a active low reset input to the FPGA.
##
# set_property PACKAGE_PIN AP7      [get_ports "SYS_RSTN"]  ;# Bank  75 VCCO - VCC1V8   - IO_L2N_T0L_N3_75
# set_property IOSTANDARD  LVCMOS12 [get_ports "SYS_RSTN"]  ;# Bank  75 VCCO - VCC1V8   - IO_L2N_T0L_N3_75

#--------------------------------------------
# Bank 75  FPGA UART Interface to FTDI FT4232 Port 3 of 4 (User selectable Baud)
#    USB_UART_RX  Input from FT4232 UART to FPGA
#    USB_UART_TX  Output from FPGA to FT4232 UART
#
set_property PACKAGE_PIN AP10     [get_ports "UART_rxd"]  ;# Bank  75 VCCO - VCC1V8   - IO_L24N_T3U_N11_75
set_property IOSTANDARD  LVCMOS12 [get_ports "UART_rxd"]  ;# Bank  75 VCCO - VCC1V8   - IO_L24N_T3U_N11_75
set_property PACKAGE_PIN AR9      [get_ports "UART_txd"]  ;# Bank  75 VCCO - VCC1V8   - IO_T3U_N12_75
set_property IOSTANDARD  LVCMOS12 [get_ports "UART_txd"]  ;# Bank  75 VCCO - VCC1V8   - IO_T3U_N12_75

#--------------------------------------------
## GT Interface
set_property PACKAGE_PIN M5    [get_ports "ETH_GT_gtx_p[3]"]
set_property PACKAGE_PIN P5    [get_ports "ETH_GT_gtx_p[2]"]
set_property PACKAGE_PIN T5    [get_ports "ETH_GT_gtx_p[1]"]
set_property PACKAGE_PIN V5    [get_ports "ETH_GT_gtx_p[0]"]
set_property PACKAGE_PIN M4    [get_ports "ETH_GT_gtx_n[3]"]
set_property PACKAGE_PIN P4    [get_ports "ETH_GT_gtx_n[2]"]
set_property PACKAGE_PIN T4    [get_ports "ETH_GT_gtx_n[1]"]
set_property PACKAGE_PIN V4    [get_ports "ETH_GT_gtx_n[0]"]

set_property PACKAGE_PIN N2    [get_ports "ETH_GT_grx_p[3]"]
set_property PACKAGE_PIN R2    [get_ports "ETH_GT_grx_p[2]"]
set_property PACKAGE_PIN U2    [get_ports "ETH_GT_grx_p[1]"]
set_property PACKAGE_PIN W2    [get_ports "ETH_GT_grx_p[0]"]
set_property PACKAGE_PIN N1    [get_ports "ETH_GT_grx_n[3]"]
set_property PACKAGE_PIN R1    [get_ports "ETH_GT_grx_n[2]"]
set_property PACKAGE_PIN U1    [get_ports "ETH_GT_grx_n[1]"]
set_property PACKAGE_PIN W1    [get_ports "ETH_GT_grx_n[0]"]

set_property PACKAGE_PIN Y5    [get_ports "GIG_GT_gtx_p[3]"]
set_property PACKAGE_PIN AB5   [get_ports "GIG_GT_gtx_p[2]"]
set_property PACKAGE_PIN AD5   [get_ports "GIG_GT_gtx_p[1]"]
set_property PACKAGE_PIN AF5   [get_ports "GIG_GT_gtx_p[0]"]
set_property PACKAGE_PIN Y4    [get_ports "GIG_GT_gtx_n[3]"]
set_property PACKAGE_PIN AB4   [get_ports "GIG_GT_gtx_n[2]"]
set_property PACKAGE_PIN AD4   [get_ports "GIG_GT_gtx_n[1]"]
set_property PACKAGE_PIN AF4   [get_ports "GIG_GT_gtx_n[0]"]

set_property PACKAGE_PIN AA2   [get_ports "GIG_GT_grx_p[3]"]
set_property PACKAGE_PIN AC2   [get_ports "GIG_GT_grx_p[2]"]
set_property PACKAGE_PIN AE2   [get_ports "GIG_GT_grx_p[1]"]
set_property PACKAGE_PIN AG2   [get_ports "GIG_GT_grx_p[0]"]
set_property PACKAGE_PIN AA1   [get_ports "GIG_GT_grx_n[3]"]
set_property PACKAGE_PIN AC1   [get_ports "GIG_GT_grx_n[2]"]
set_property PACKAGE_PIN AE1   [get_ports "GIG_GT_grx_n[1]"]
set_property PACKAGE_PIN AG1   [get_ports "GIG_GT_grx_n[0]"]


#--------------------------------------------
# Soft DDR4 Controller on PL
#
set_property PACKAGE_PIN AP14  [get_ports MEMPL_CLK_clk_p]
set_property PACKAGE_PIN AR15  [get_ports MEMPL_CLK_clk_n]
set_property IOSTANDARD LVDS15 [get_ports MEMPL_CLK_clk_n]
set_property IOSTANDARD LVDS15 [get_ports MEMPL_CLK_clk_p]
# create_clock -period 10.000 -name MEMPL_CLK [get_ports "MEMPL_CLK_clk_p"]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_c[0]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_c[1]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_c[2]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_c[3]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_c[4]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_c[5]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_c[6]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_c[7]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_c[8]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_t[0]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_t[1]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_t[2]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_t[3]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_t[4]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_t[5]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_t[6]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_t[7]}]
set_property IOSTANDARD DIFF_POD12 [get_ports {DDR4PL_dqs_t[8]}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports {DDR4PL_ck_c[0]}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports {DDR4PL_ck_t[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports DDR4PL_alert_n]
set_property IOSTANDARD LVCMOS12 [get_ports DDR4PL_reset_n]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dm_n[0]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dm_n[1]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dm_n[2]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dm_n[3]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dm_n[4]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dm_n[5]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dm_n[6]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dm_n[7]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dm_n[8]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[0]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[10]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[11]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[12]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[13]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[14]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[15]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[16]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[17]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[18]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[19]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[1]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[20]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[21]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[22]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[23]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[24]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[25]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[26]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[27]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[28]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[29]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[2]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[30]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[31]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[32]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[33]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[34]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[35]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[36]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[37]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[38]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[39]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[3]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[40]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[41]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[42]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[43]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[44]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[45]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[46]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[47]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[48]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[49]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[4]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[50]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[51]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[52]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[53]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[54]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[55]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[56]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[57]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[58]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[59]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[5]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[60]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[61]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[62]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[63]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[64]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[65]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[66]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[67]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[68]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[69]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[6]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[70]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[71]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[7]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[8]}]
set_property IOSTANDARD POD12 [get_ports {DDR4PL_dq[9]}]
set_property IOSTANDARD SSTL12 [get_ports DDR4PL_act_n]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[0]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[10]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[11]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[12]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[13]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[14]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[15]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[16]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[1]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[2]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[3]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[4]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[5]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[6]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[7]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[8]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_adr[9]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_ba[0]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_ba[1]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_bg[0]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_bg[1]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_cke[0]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_cs_n[0]}]
set_property IOSTANDARD SSTL12 [get_ports {DDR4PL_odt[0]}]
set_property IOSTANDARD SSTL12 [get_ports DDR4PL_par]
set_property DRIVE 8 [get_ports DDR4PL_reset_n]
set_property PACKAGE_PIN AN4 [get_ports DDR4PL_act_n]
set_property PACKAGE_PIN AV5 [get_ports {DDR4PL_adr[0]}]
set_property PACKAGE_PIN AN3 [get_ports {DDR4PL_adr[10]}]
set_property PACKAGE_PIN AP3 [get_ports {DDR4PL_adr[11]}]
set_property PACKAGE_PIN AM6 [get_ports {DDR4PL_adr[12]}]
set_property PACKAGE_PIN AN5 [get_ports {DDR4PL_adr[13]}]
set_property PACKAGE_PIN AP2 [get_ports {DDR4PL_adr[14]}]
set_property PACKAGE_PIN AR1 [get_ports {DDR4PL_adr[15]}]
set_property PACKAGE_PIN AM2 [get_ports {DDR4PL_adr[16]}]
set_property PACKAGE_PIN AU5 [get_ports {DDR4PL_adr[1]}]
set_property PACKAGE_PIN AT3 [get_ports {DDR4PL_adr[2]}]
set_property PACKAGE_PIN AU2 [get_ports {DDR4PL_adr[3]}]
set_property PACKAGE_PIN AU3 [get_ports {DDR4PL_adr[4]}]
set_property PACKAGE_PIN AT4 [get_ports {DDR4PL_adr[5]}]
set_property PACKAGE_PIN AT1 [get_ports {DDR4PL_adr[6]}]
set_property PACKAGE_PIN AU1 [get_ports {DDR4PL_adr[7]}]
set_property PACKAGE_PIN AT5 [get_ports {DDR4PL_adr[8]}]
set_property PACKAGE_PIN AU6 [get_ports {DDR4PL_adr[9]}]
set_property PACKAGE_PIN AJ5 [get_ports DDR4PL_alert_n]
set_property PACKAGE_PIN AP1 [get_ports {DDR4PL_ba[0]}]
set_property PACKAGE_PIN AM5 [get_ports {DDR4PL_ba[1]}]
set_property PACKAGE_PIN AM3 [get_ports {DDR4PL_bg[0]}]
set_property PACKAGE_PIN AN1 [get_ports {DDR4PL_bg[1]}]
set_property PACKAGE_PIN AU7 [get_ports {DDR4PL_ck_t[0]}]
set_property PACKAGE_PIN AV7 [get_ports {DDR4PL_ck_c[0]}]
set_property PACKAGE_PIN AH4 [get_ports {DDR4PL_cke[0]}]
set_property PACKAGE_PIN AH5 [get_ports {DDR4PL_cs_n[0]}]
set_property PACKAGE_PIN AV17 [get_ports {DDR4PL_dm_n[0]}]
set_property PACKAGE_PIN AU15 [get_ports {DDR4PL_dm_n[1]}]
set_property PACKAGE_PIN AN15 [get_ports {DDR4PL_dm_n[2]}]
set_property PACKAGE_PIN AH14 [get_ports {DDR4PL_dm_n[3]}]
set_property PACKAGE_PIN AU12 [get_ports {DDR4PL_dm_n[4]}]
set_property PACKAGE_PIN AY9 [get_ports {DDR4PL_dm_n[5]}]
set_property PACKAGE_PIN AL10 [get_ports {DDR4PL_dm_n[6]}]
set_property PACKAGE_PIN AK7 [get_ports {DDR4PL_dm_n[7]}]
set_property PACKAGE_PIN AY3 [get_ports {DDR4PL_dm_n[8]}]
set_property PACKAGE_PIN AW19 [get_ports {DDR4PL_dq[0]}]
set_property PACKAGE_PIN AV15 [get_ports {DDR4PL_dq[10]}]
set_property PACKAGE_PIN AV14 [get_ports {DDR4PL_dq[11]}]
set_property PACKAGE_PIN AT14 [get_ports {DDR4PL_dq[12]}]
set_property PACKAGE_PIN AT13 [get_ports {DDR4PL_dq[13]}]
set_property PACKAGE_PIN AT18 [get_ports {DDR4PL_dq[14]}]
set_property PACKAGE_PIN AU17 [get_ports {DDR4PL_dq[15]}]
set_property PACKAGE_PIN AL17 [get_ports {DDR4PL_dq[16]}]
set_property PACKAGE_PIN AM18 [get_ports {DDR4PL_dq[17]}]
set_property PACKAGE_PIN AL14 [get_ports {DDR4PL_dq[18]}]
set_property PACKAGE_PIN AM14 [get_ports {DDR4PL_dq[19]}]
set_property PACKAGE_PIN AY19 [get_ports {DDR4PL_dq[1]}]
set_property PACKAGE_PIN AM13 [get_ports {DDR4PL_dq[20]}]
set_property PACKAGE_PIN AN13 [get_ports {DDR4PL_dq[21]}]
set_property PACKAGE_PIN AM17 [get_ports {DDR4PL_dq[22]}]
set_property PACKAGE_PIN AN17 [get_ports {DDR4PL_dq[23]}]
set_property PACKAGE_PIN AJ18 [get_ports {DDR4PL_dq[24]}]
set_property PACKAGE_PIN AK18 [get_ports {DDR4PL_dq[25]}]
set_property PACKAGE_PIN AH13 [get_ports {DDR4PL_dq[26]}]
set_property PACKAGE_PIN AJ14 [get_ports {DDR4PL_dq[27]}]
set_property PACKAGE_PIN AK13 [get_ports {DDR4PL_dq[28]}]
set_property PACKAGE_PIN AL13 [get_ports {DDR4PL_dq[29]}]
set_property PACKAGE_PIN AW15 [get_ports {DDR4PL_dq[2]}]
set_property PACKAGE_PIN AJ17 [get_ports {DDR4PL_dq[30]}]
set_property PACKAGE_PIN AK16 [get_ports {DDR4PL_dq[31]}]
set_property PACKAGE_PIN AW12 [get_ports {DDR4PL_dq[32]}]
set_property PACKAGE_PIN AY13 [get_ports {DDR4PL_dq[33]}]
set_property PACKAGE_PIN AT11 [get_ports {DDR4PL_dq[34]}]
set_property PACKAGE_PIN AU11 [get_ports {DDR4PL_dq[35]}]
set_property PACKAGE_PIN AR11 [get_ports {DDR4PL_dq[36]}]
set_property PACKAGE_PIN AT10 [get_ports {DDR4PL_dq[37]}]
set_property PACKAGE_PIN AW11 [get_ports {DDR4PL_dq[38]}]
set_property PACKAGE_PIN AY12 [get_ports {DDR4PL_dq[39]}]
set_property PACKAGE_PIN AY15 [get_ports {DDR4PL_dq[3]}]
set_property PACKAGE_PIN AT9 [get_ports {DDR4PL_dq[40]}]
set_property PACKAGE_PIN AT8 [get_ports {DDR4PL_dq[41]}]
set_property PACKAGE_PIN AW9 [get_ports {DDR4PL_dq[42]}]
set_property PACKAGE_PIN AY8 [get_ports {DDR4PL_dq[43]}]
set_property PACKAGE_PIN AU8 [get_ports {DDR4PL_dq[44]}]
set_property PACKAGE_PIN AV8 [get_ports {DDR4PL_dq[45]}]
set_property PACKAGE_PIN AU10 [get_ports {DDR4PL_dq[46]}]
set_property PACKAGE_PIN AV10 [get_ports {DDR4PL_dq[47]}]
set_property PACKAGE_PIN AH11 [get_ports {DDR4PL_dq[48]}]
set_property PACKAGE_PIN AH10 [get_ports {DDR4PL_dq[49]}]
set_property PACKAGE_PIN AW14 [get_ports {DDR4PL_dq[4]}]
set_property PACKAGE_PIN AM11 [get_ports {DDR4PL_dq[50]}]
set_property PACKAGE_PIN AN11 [get_ports {DDR4PL_dq[51]}]
set_property PACKAGE_PIN AM10 [get_ports {DDR4PL_dq[52]}]
set_property PACKAGE_PIN AM9 [get_ports {DDR4PL_dq[53]}]
set_property PACKAGE_PIN AJ12 [get_ports {DDR4PL_dq[54]}]
set_property PACKAGE_PIN AK12 [get_ports {DDR4PL_dq[55]}]
set_property PACKAGE_PIN AH8 [get_ports {DDR4PL_dq[56]}]
set_property PACKAGE_PIN AH7 [get_ports {DDR4PL_dq[57]}]
set_property PACKAGE_PIN AN9 [get_ports {DDR4PL_dq[58]}]
set_property PACKAGE_PIN AN8 [get_ports {DDR4PL_dq[59]}]
set_property PACKAGE_PIN AY14 [get_ports {DDR4PL_dq[5]}]
set_property PACKAGE_PIN AM7 [get_ports {DDR4PL_dq[60]}]
set_property PACKAGE_PIN AN7 [get_ports {DDR4PL_dq[61]}]
set_property PACKAGE_PIN AJ9 [get_ports {DDR4PL_dq[62]}]
set_property PACKAGE_PIN AJ8 [get_ports {DDR4PL_dq[63]}]
set_property PACKAGE_PIN AW7 [get_ports {DDR4PL_dq[64]}]
set_property PACKAGE_PIN AY7 [get_ports {DDR4PL_dq[65]}]
set_property PACKAGE_PIN AV4 [get_ports {DDR4PL_dq[66]}]
set_property PACKAGE_PIN AV3 [get_ports {DDR4PL_dq[67]}]
set_property PACKAGE_PIN AV2 [get_ports {DDR4PL_dq[68]}]
set_property PACKAGE_PIN AW2 [get_ports {DDR4PL_dq[69]}]
set_property PACKAGE_PIN AY18 [get_ports {DDR4PL_dq[6]}]
set_property PACKAGE_PIN AW6 [get_ports {DDR4PL_dq[70]}]
set_property PACKAGE_PIN AY5 [get_ports {DDR4PL_dq[71]}]
set_property PACKAGE_PIN AY17 [get_ports {DDR4PL_dq[7]}]
set_property PACKAGE_PIN AU18 [get_ports {DDR4PL_dq[8]}]
set_property PACKAGE_PIN AV19 [get_ports {DDR4PL_dq[9]}]
set_property PACKAGE_PIN AV18 [get_ports {DDR4PL_dqs_t[0]}]
set_property PACKAGE_PIN AW17 [get_ports {DDR4PL_dqs_c[0]}]
set_property PACKAGE_PIN AT16 [get_ports {DDR4PL_dqs_t[1]}]
set_property PACKAGE_PIN AU16 [get_ports {DDR4PL_dqs_c[1]}]
set_property PACKAGE_PIN AN16 [get_ports {DDR4PL_dqs_t[2]}]
set_property PACKAGE_PIN AM15 [get_ports {DDR4PL_dqs_c[2]}]
set_property PACKAGE_PIN AL16 [get_ports {DDR4PL_dqs_t[3]}]
set_property PACKAGE_PIN AK15 [get_ports {DDR4PL_dqs_c[3]}]
set_property PACKAGE_PIN AV13 [get_ports {DDR4PL_dqs_t[4]}]
set_property PACKAGE_PIN AV12 [get_ports {DDR4PL_dqs_c[4]}]
set_property PACKAGE_PIN AV9 [get_ports {DDR4PL_dqs_t[5]}]
set_property PACKAGE_PIN AW10 [get_ports {DDR4PL_dqs_c[5]}]
set_property PACKAGE_PIN AJ11 [get_ports {DDR4PL_dqs_t[6]}]
set_property PACKAGE_PIN AK10 [get_ports {DDR4PL_dqs_c[6]}]
set_property PACKAGE_PIN AK9 [get_ports {DDR4PL_dqs_t[7]}]
set_property PACKAGE_PIN AL8 [get_ports {DDR4PL_dqs_c[7]}]
set_property PACKAGE_PIN AW5 [get_ports {DDR4PL_dqs_t[8]}]
set_property PACKAGE_PIN AY4 [get_ports {DDR4PL_dqs_c[8]}]
set_property PACKAGE_PIN AJ6 [get_ports {DDR4PL_odt[0]}]
set_property PACKAGE_PIN AJ3 [get_ports DDR4PL_par]
set_property PACKAGE_PIN AK3 [get_ports DDR4PL_reset_n]

#--------------------------------------------
# Hard DDR4 Controller inside NOC
#
set_property IOSTANDARD LVDS15  [get_ports {MEM_CLK_clk_n[0]}]
set_property PACKAGE_PIN AG36   [get_ports {MEM_CLK_clk_p[0]}]
set_property PACKAGE_PIN AG37   [get_ports {MEM_CLK_clk_n[0]}]
set_property IOSTANDARD LVDS15  [get_ports {MEM_CLK_clk_p[0]}]
# create_clock -period 10.000 -name MEM_CLK [get_ports "MEM_CLK_clk_p"]
set_property PACKAGE_PIN AV35 [get_ports {DDR4_act_n[0]}]
set_property PACKAGE_PIN AN37 [get_ports {DDR4_adr[0]}]
set_property PACKAGE_PIN AT35 [get_ports {DDR4_adr[10]}]
set_property PACKAGE_PIN AV39 [get_ports {DDR4_adr[11]}]
set_property PACKAGE_PIN AV38 [get_ports {DDR4_adr[12]}]
set_property PACKAGE_PIN AU37 [get_ports {DDR4_adr[13]}]
set_property PACKAGE_PIN AP36 [get_ports {DDR4_adr[14]}]
set_property PACKAGE_PIN AR35 [get_ports {DDR4_adr[15]}]
set_property PACKAGE_PIN AN40 [get_ports {DDR4_adr[16]}]
set_property PACKAGE_PIN AW39 [get_ports {DDR4_adr[1]}]
set_property PACKAGE_PIN AU40 [get_ports {DDR4_adr[2]}]
set_property PACKAGE_PIN AT36 [get_ports {DDR4_adr[3]}]
set_property PACKAGE_PIN AP39 [get_ports {DDR4_adr[4]}]
set_property PACKAGE_PIN AR39 [get_ports {DDR4_adr[5]}]
set_property PACKAGE_PIN AR38 [get_ports {DDR4_adr[6]}]
set_property PACKAGE_PIN AY37 [get_ports {DDR4_adr[7]}]
set_property PACKAGE_PIN AP40 [get_ports {DDR4_adr[8]}]
set_property PACKAGE_PIN AU38 [get_ports {DDR4_adr[9]}]
set_property PACKAGE_PIN AE37 [get_ports {DDR4_alert_n[0]}]
set_property PACKAGE_PIN AW36 [get_ports {DDR4_ba[0]}]
set_property PACKAGE_PIN AN39 [get_ports {DDR4_ba[1]}]
set_property PACKAGE_PIN AU35 [get_ports {DDR4_bg[0]}]
set_property PACKAGE_PIN AY38 [get_ports {DDR4_bg[1]}]
set_property PACKAGE_PIN AV37 [get_ports {DDR4_ck_c[0]}]
set_property PACKAGE_PIN AW37 [get_ports {DDR4_ck_t[0]}]
set_property PACKAGE_PIN AV40 [get_ports {DDR4_cke[0]}]
set_property PACKAGE_PIN AR36 [get_ports {DDR4_cs_n[0]}]
set_property PACKAGE_PIN AY33 [get_ports {DDR4_dm_n[0]}]
set_property PACKAGE_PIN AR33 [get_ports {DDR4_dm_n[1]}]
set_property PACKAGE_PIN AU27 [get_ports {DDR4_dm_n[2]}]
set_property PACKAGE_PIN AV28 [get_ports {DDR4_dm_n[3]}]
set_property PACKAGE_PIN AG40 [get_ports {DDR4_dm_n[4]}]
set_property PACKAGE_PIN AK38 [get_ports {DDR4_dm_n[5]}]
set_property PACKAGE_PIN AK35 [get_ports {DDR4_dm_n[6]}]
set_property PACKAGE_PIN AL33 [get_ports {DDR4_dm_n[7]}]
set_property PACKAGE_PIN AP27 [get_ports {DDR4_dm_n[8]}]
set_property PACKAGE_PIN AV34 [get_ports {DDR4_dq[0]}]
set_property PACKAGE_PIN AR32 [get_ports {DDR4_dq[10]}]
set_property PACKAGE_PIN AP31 [get_ports {DDR4_dq[11]}]
set_property PACKAGE_PIN AT33 [get_ports {DDR4_dq[12]}]
set_property PACKAGE_PIN AT34 [get_ports {DDR4_dq[13]}]
set_property PACKAGE_PIN AN33 [get_ports {DDR4_dq[14]}]
set_property PACKAGE_PIN AN34 [get_ports {DDR4_dq[15]}]
set_property PACKAGE_PIN AU26 [get_ports {DDR4_dq[16]}]
set_property PACKAGE_PIN AT26 [get_ports {DDR4_dq[17]}]
set_property PACKAGE_PIN AV30 [get_ports {DDR4_dq[18]}]
set_property PACKAGE_PIN AU31 [get_ports {DDR4_dq[19]}]
set_property PACKAGE_PIN AW34 [get_ports {DDR4_dq[1]}]
set_property PACKAGE_PIN AT25 [get_ports {DDR4_dq[20]}]
set_property PACKAGE_PIN AU25 [get_ports {DDR4_dq[21]}]
set_property PACKAGE_PIN AU30 [get_ports {DDR4_dq[22]}]
set_property PACKAGE_PIN AT30 [get_ports {DDR4_dq[23]}]
set_property PACKAGE_PIN AW27 [get_ports {DDR4_dq[24]}]
set_property PACKAGE_PIN AY27 [get_ports {DDR4_dq[25]}]
set_property PACKAGE_PIN AY30 [get_ports {DDR4_dq[26]}]
set_property PACKAGE_PIN AW31 [get_ports {DDR4_dq[27]}]
set_property PACKAGE_PIN AV27 [get_ports {DDR4_dq[28]}]
set_property PACKAGE_PIN AW26 [get_ports {DDR4_dq[29]}]
set_property PACKAGE_PIN AY32 [get_ports {DDR4_dq[2]}]
set_property PACKAGE_PIN AY29 [get_ports {DDR4_dq[30]}]
set_property PACKAGE_PIN AW30 [get_ports {DDR4_dq[31]}]
set_property PACKAGE_PIN AJ40 [get_ports {DDR4_dq[32]}]
set_property PACKAGE_PIN AH40 [get_ports {DDR4_dq[33]}]
set_property PACKAGE_PIN AC40 [get_ports {DDR4_dq[34]}]
set_property PACKAGE_PIN AC39 [get_ports {DDR4_dq[35]}]
set_property PACKAGE_PIN AM40 [get_ports {DDR4_dq[36]}]
set_property PACKAGE_PIN AL40 [get_ports {DDR4_dq[37]}]
set_property PACKAGE_PIN AD40 [get_ports {DDR4_dq[38]}]
set_property PACKAGE_PIN AD39 [get_ports {DDR4_dq[39]}]
set_property PACKAGE_PIN AW32 [get_ports {DDR4_dq[3]}]
set_property PACKAGE_PIN AK39 [get_ports {DDR4_dq[40]}]
set_property PACKAGE_PIN AL38 [get_ports {DDR4_dq[41]}]
set_property PACKAGE_PIN AE38 [get_ports {DDR4_dq[42]}]
set_property PACKAGE_PIN AD37 [get_ports {DDR4_dq[43]}]
set_property PACKAGE_PIN AL39 [get_ports {DDR4_dq[44]}]
set_property PACKAGE_PIN AM38 [get_ports {DDR4_dq[45]}]
set_property PACKAGE_PIN AG38 [get_ports {DDR4_dq[46]}]
set_property PACKAGE_PIN AF38 [get_ports {DDR4_dq[47]}]
set_property PACKAGE_PIN AL36 [get_ports {DDR4_dq[48]}]
set_property PACKAGE_PIN AL35 [get_ports {DDR4_dq[49]}]
set_property PACKAGE_PIN AU32 [get_ports {DDR4_dq[4]}]
set_property PACKAGE_PIN AD36 [get_ports {DDR4_dq[50]}]
set_property PACKAGE_PIN AD35 [get_ports {DDR4_dq[51]}]
set_property PACKAGE_PIN AM35 [get_ports {DDR4_dq[52]}]
set_property PACKAGE_PIN AM36 [get_ports {DDR4_dq[53]}]
set_property PACKAGE_PIN AE36 [get_ports {DDR4_dq[54]}]
set_property PACKAGE_PIN AF35 [get_ports {DDR4_dq[55]}]
set_property PACKAGE_PIN AM33 [get_ports {DDR4_dq[56]}]
set_property PACKAGE_PIN AM34 [get_ports {DDR4_dq[57]}]
set_property PACKAGE_PIN AK31 [get_ports {DDR4_dq[58]}]
set_property PACKAGE_PIN AJ31 [get_ports {DDR4_dq[59]}]
set_property PACKAGE_PIN AV32 [get_ports {DDR4_dq[5]}]
set_property PACKAGE_PIN AL31 [get_ports {DDR4_dq[60]}]
set_property PACKAGE_PIN AM31 [get_ports {DDR4_dq[61]}]
set_property PACKAGE_PIN AK32 [get_ports {DDR4_dq[62]}]
set_property PACKAGE_PIN AJ32 [get_ports {DDR4_dq[63]}]
set_property PACKAGE_PIN AM27 [get_ports {DDR4_dq[64]}]
set_property PACKAGE_PIN AM26 [get_ports {DDR4_dq[65]}]
set_property PACKAGE_PIN AL29 [get_ports {DDR4_dq[66]}]
set_property PACKAGE_PIN AM30 [get_ports {DDR4_dq[67]}]
set_property PACKAGE_PIN AN25 [get_ports {DDR4_dq[68]}]
set_property PACKAGE_PIN AM25 [get_ports {DDR4_dq[69]}]
set_property PACKAGE_PIN AW35 [get_ports {DDR4_dq[6]}]
set_property PACKAGE_PIN AN29 [get_ports {DDR4_dq[70]}]
set_property PACKAGE_PIN AM29 [get_ports {DDR4_dq[71]}]
set_property PACKAGE_PIN AY35 [get_ports {DDR4_dq[7]}]
set_property PACKAGE_PIN AN31 [get_ports {DDR4_dq[8]}]
set_property PACKAGE_PIN AN32 [get_ports {DDR4_dq[9]}]
set_property PACKAGE_PIN AU33 [get_ports {DDR4_dqs_t[0]}]
set_property PACKAGE_PIN AV33 [get_ports {DDR4_dqs_c[0]}]
set_property PACKAGE_PIN AP34 [get_ports {DDR4_dqs_t[1]}]
set_property PACKAGE_PIN AP35 [get_ports {DDR4_dqs_c[1]}]
set_property PACKAGE_PIN AT29 [get_ports {DDR4_dqs_t[2]}]
set_property PACKAGE_PIN AU28 [get_ports {DDR4_dqs_c[2]}]
set_property PACKAGE_PIN AW29 [get_ports {DDR4_dqs_t[3]}]
set_property PACKAGE_PIN AY28 [get_ports {DDR4_dqs_c[3]}]
set_property PACKAGE_PIN AE39 [get_ports {DDR4_dqs_t[4]}]
set_property PACKAGE_PIN AF40 [get_ports {DDR4_dqs_c[4]}]
set_property PACKAGE_PIN AH38 [get_ports {DDR4_dqs_t[5]}]
set_property PACKAGE_PIN AH39 [get_ports {DDR4_dqs_c[5]}]
set_property PACKAGE_PIN AG35 [get_ports {DDR4_dqs_t[6]}]
set_property PACKAGE_PIN AH35 [get_ports {DDR4_dqs_c[6]}]
set_property PACKAGE_PIN AJ34 [get_ports {DDR4_dqs_t[7]}]
set_property PACKAGE_PIN AK34 [get_ports {DDR4_dqs_c[7]}]
set_property PACKAGE_PIN AP29 [get_ports {DDR4_dqs_t[8]}]
set_property PACKAGE_PIN AN28 [get_ports {DDR4_dqs_c[8]}]
set_property PACKAGE_PIN AU36 [get_ports {DDR4_odt[0]}]
set_property PACKAGE_PIN AN38 [get_ports {DDR4_par[0]}]
set_property PACKAGE_PIN AF36 [get_ports {DDR4_reset_n[0]}]
